import { NextPage } from "next";
import Head from "next/head";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Om</title>
        <meta name="om" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-10 grid grid-cols-1 content-center gap-1">
        <h1 className='className="text-2xl dark:text-white" font-bold tracking-tight text-gray-900'>
          Om
        </h1>
        <p className="font-normal text-gray-700 dark:text-gray-400">
          ENHS Fueling System er en digital løsning for å holde orden på
          flyplassen sin fueling kapasitet. Systemet sier automatisk fra til
          administrator når tanken begynner å nærme seg tom, slik at flyene ikke
          unødvendig står på bakken. Smart ikke sant?
        </p>
      </div>
    </>
  );
};

export default About;
