import { type NextPage } from "next";
import Head from "next/head";
import UIRegisterFuel from '../../components/UIRegisterFuel';

const Register: NextPage = () => {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="register" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UIRegisterFuel/>
    </>
  );
};

export default Register;
