import { type NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/trpc";
import UITable from "../components/UITable";
import PumpStat from "../components/PumpStat";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PumpStat />
      <UITable />
    </>
  );
};

export default Home;
