import { type NextPage } from "next";
import Head from "next/head";


const Admin: NextPage = () => {

  return (
    <>
        <Head>
          <title>Admin</title>
          <meta name="admin" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
    </>
  );
};

export default Admin;
